spring.application.name=exhibition-timeslot-booking
server.port=8080
spring.profiles.active=secret, dev

spring.datasource.url=jdbc:mysql://localhost:3306/mini-exhibition-db

file.upload.base-path=${user.dir}/upload

file.upload.user-profil=user/profile

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=100MB

jwt.expiration=600000
jwt.refresh-expiration=604800000
jwt.email-expiration=180000
jwt.clock-skew-seconds=60